course = "mooc-programming-24"

[exercises.part08-01_smallest_average]
id = 228737
checksum = "7b173687bf0adebc4a486a68f6c32031"

[exercises.part08-02_row_sums]
id = 228750
checksum = "d9973e48318dc29c3327e7897d41ec80"

[exercises.part08-03_list_years]
id = 228738
checksum = "34204b1e729dbe3f9e230ece01aff8bb"

[exercises.part08-04_shopping_list]
id = 228751
checksum = "ae99378be7d856870fd842230850b805"

[exercises.part08-05_book]
id = 228748
checksum = "aac905bf98e296530348a26ce1d62953"

[exercises.part08-06_three_classes]
id = 228749
checksum = "db0a8040524583a0b511483cf1ce31a0"

[exercises.part08-07_pet]
id = 228739
checksum = "b7a475be3b4f573b0e662c62d56c53db"

[exercises.part08-08_older_book]
id = 228745
checksum = "ec8edbf83ca00f4ec521f446208bbb97"

[exercises.part08-09_books_of_genre]
id = 228740
checksum = "8a92d4e749d53c617b4e0624f9604e43"

[exercises.part08-10_decreasing_counter]
id = 228742
checksum = "baa34ecdf760cdde32cc3fbdf5536d12"

[exercises.part08-11_first_and_last_name]
id = 228743
checksum = "b106215b92f30bfe45dab2b229bc4fa7"

[exercises.part08-12_number_stats]
id = 228744
checksum = "7b15d1eb9de2227eea1a319ac5a9b71b"

[exercises.part08-13_stopwatch]
id = 228747
checksum = "2d59af6633c662644f62bddb79d2a0ce"

[exercises.part08-14_clock]
id = 228746
checksum = "9326d9c6edfc221351a6d919b01f4b54"

[exercises.part08-15_lunchcard]
id = 228752
checksum = "de1dd39ddb02a80fc5ac43d905a0207f"

[exercises.part08-16_series]
id = 228741
checksum = "cc7e178145f70ef2440ffcf972d5e79e"

[exercises.part09-01_fastest_car]
id = 228806
checksum = "5c92c0748d08f4c30991ab9ce461af58"

[exercises.part09-02_passing_submissions]
id = 228805
checksum = "fd62c8b5668c6554acbea13cc44efc44"

[exercises.part09-03_baby_centre]
id = 228798
checksum = "8a1920343eb9a76b20da5a1108c9e6df"

[exercises.part09-04_lunchcard_and_paymentterminal]
id = 228793
checksum = "cffc0c94e6e88b59f6e9e39b459fa812"

[exercises.part09-05_comparing_properties]
id = 228800
checksum = "f84df8c676e5754e99578443bc6ec385"

[exercises.part09-06_pets]
id = 228801
checksum = "5d59bed6b1812f2810cb8cce176f953f"

[exercises.part09-07_box_of_presents]
id = 228792
checksum = "12134adc29f90795f814b7b6148f84b9"

[exercises.part09-08_shortest_in_room]
id = 228803
checksum = "79b612f68fabb9ce422ad4233f2c3b6a"

[exercises.part09-09_car]
id = 228802
checksum = "2b97108b7802ff72a4ab794926e817ef"

[exercises.part09-10_recording]
id = 228795
checksum = "b0bb4fa38607ad2760e9cfdffed939c7"

[exercises.part09-11_weather_station]
id = 228797
checksum = "4c95dfa9122553c816af249dd6fda33e"

[exercises.part09-12_service_charge]
id = 228799
checksum = "f5f0fb9cdd5ba3769ce46030f7b298b7"

[exercises.part09-13_postcodes]
id = 228804
checksum = "a664fc51b4042799d0a122f494da72d4"

[exercises.part09-14_list_helper]
id = 228796
checksum = "60cae6fb12085068d1effba1b960f411"

[exercises.part09-15_item_suitcase_hold]
id = 228794
checksum = "9887a7260d0779c3546e5a57bb0feebd"

[exercises.part10-01_laptop_computer]
id = 228789
checksum = "d3cc52fa293407a3b9f5c530048c6985"

[exercises.part10-02_game_museum]
id = 228787
checksum = "d6879c3d7ab4bb5ba9f8ef1a71dc764f"

[exercises.part10-03_areas]
id = 228791
checksum = "92a26ec165d30412af3fbe6677403e4d"

[exercises.part10-04_word_game]
id = 228781
checksum = "b7b87f0778c36c81eee64a27c7630687"

[exercises.part10-05_supergroup]
id = 228782
checksum = "ebcf56154970a9cb56641f058c3f17fa"

[exercises.part10-06_secret_magic_potion]
id = 228784
checksum = "046fc36f18233f55c136b4600ec18f63"

[exercises.part10-07_money]
id = 228785
checksum = "212544ea576eee1770f3086785f65777"

[exercises.part10-08_simple_date]
id = 228783
checksum = "a582e1778b169d42b0abe96dfe3cf7a3"

[exercises.part10-09_iterable_shopping_list]
id = 228786
checksum = "c855e3a427bc472ab5a07c066a19b0ea"

[exercises.part10-10_phone_book_v1]
id = 228790
checksum = "dc5a7c94c16f7c320e5bfb8c1bee6c39"

[exercises.part10-11_phone_book_v2]
id = 228788
checksum = "2d92548a10df72760f7c2960b4be8bbb"

[exercises.part10-12_course_records]
id = 228780
checksum = "91b224b1823a1142dc1d57cbde900236"
